Update Build_ax6000_immortalwrt_237_golang_msd_lite_110m.yml

diff --git a/.github/workflows/Build_ax6000_immortalwrt_237_golang_msd_lite_110m.yml b/.github/workflows/Build_ax6000_immortalwrt_237_golang_msd_lite_110m.yml
--- a/.github/workflows/Build_ax6000_immortalwrt_237_golang_msd_lite_110m.yml
+++ b/.github/workflows/Build_ax6000_immortalwrt_237_golang_msd_lite_110m.yml
@@ -156,9 +156,15 @@ jobs:
     - name: 升级 Passwall 工具链为 golang1.27
       working-directory: /builder/openwrt
       run: |
-        # 1. 直接将本地仓库根目录下的 golang1.27 复制到 feeds 目录，并改名 golang
-        rm -rf feeds/packages/lang/golang
-        cp -rf "$GITHUB_WORKSPACE/golang1.27" feeds/packages/lang/golang
+        # 1. 直接将本地仓库根目录下的 golang1.27 复制到 feeds 目录，并改名 golang，没有复制成功，自动退出
+        if [ -d "$GITHUB_WORKSPACE/golang1.27" ]; then
+          rm -rf feeds/packages/lang/golang
+          cp -rf "$GITHUB_WORKSPACE/golang1.27" feeds/packages/lang/golang
+          echo "Successfully replaced golang with local golang1.27"
+        else
+          echo "Error: $GITHUB_WORKSPACE/golang1.27 directory not found!"
+          exit 1
+        fi
         
         # 2. 删除临时目录，确保系统重新扫描新 replace 进来的 Makefile
         rm -rf tmp
@@ -173,7 +179,7 @@ jobs:
       run: |
         ./scripts/feeds install -a
 
-       #======= 编入第三方 msd_lite 插件，解决 IPTV 卡顿（更新和安装 feeds 命令之后）=======
+       #======= 编入第三方 msd_lite 插件，解决 IPTV 卡顿（使用 package 编译法，更新和安装 feeds 命令之后）=======
     - name: 编入第三方 msd_lite 插件
       working-directory: /builder/openwrt
       run: |
@@ -185,7 +191,7 @@ jobs:
         # 删除临时目录
         rm -rf tmp
         
-       # ======== 1. 编译 OpenClash 最新版，使用 package 编译法（更新和安装 feeds 命令之后）推荐 =========
+       # ======== 1. 编译 OpenClash 最新版（使用 package 编译法，更新和安装 feeds 命令之后）推荐 =========
        # 不推荐使用写入 ./feeds.conf.default 编译法
        # immortalwrt 插件库已经包含 OpenClash，若源码被删除或编译 OpenClash 最新版，使用以下命令自行编译，打开 immortalwrt官方插件库查询：https://github.com/immortalwrt/immortalwrt（选择 openwrt-24.10分支，打开 feeds.conf.default文件，再打开luci仓库找到“applications”查询插件）
     #- name: Import Official Recommended OpenClash
@@ -204,7 +210,7 @@ jobs:
         # 删除临时目录
     #    rm -rf /tmp/OpenClash && rm -rf tmp
 
-       # ======== 2. 编译 Passwall 最新版，使用 package 编译法（更新和安装 feeds 命令之后）推荐 =========
+       # ======== 2. 编译 Passwall 最新版（使用 package 编译法，更新和安装 feeds 命令之后）推荐 =========
        # 不推荐使用写入 ./feeds.conf.default 编译法
        # immortalwrt 插件库已经包含 Passwall ，若源码被删除或编译最新版，使用以下命令自行编译，打开 immortalwrt官方插件库查询：https://github.com/immortalwrt/immortalwrt（选择 openwrt-24.10分支，打开 feeds.conf.default文件，再打开luci仓库找到“applications”查询插件）
     - name: Import Official Recommended Passwall
