Update Build_ax6000_immortalwrt_237_golang_msd_lite_110m.yml

diff --git a/.github/workflows/Build_ax6000_immortalwrt_237_golang_msd_lite_110m.yml b/.github/workflows/Build_ax6000_immortalwrt_237_golang_msd_lite_110m.yml
--- a/.github/workflows/Build_ax6000_immortalwrt_237_golang_msd_lite_110m.yml
+++ b/.github/workflows/Build_ax6000_immortalwrt_237_golang_msd_lite_110m.yml
@@ -152,16 +152,35 @@ jobs:
       run: |
         ./scripts/feeds update -a        
 
-       #======= 编入第三方 msd_lite 插件，解决 IPTV 卡顿（置于更新和安装 feeds 命令之间）=======
-    - name: 编入第三方 msd_lite 插件
+       #======= 解决 Passwall 的 Geoview 报错问题（置于更新和安装 feeds 命令之间）=======
+    - name: 升级 Passwall 工具链为 Golang 1.26
       working-directory: /builder/openwrt
       run: |
-        rm -rf feeds/packages/net/msd_lite
-        rm -rf feeds/luci/applications/luci-app-msd_lite
-        git clone https://github.com/ximiTech/msd_lite.git package/msd_lite
-        git clone https://github.com/ximiTech/luci-app-msd_lite.git package/luci-app-msd_lite
-               
-       # ======== 1. 编译 OpenClash 最新版，使用 package 编译法（置于更新和安装 feeds 命令之间）推荐 =========
+        # 1. 直接将本地仓库根目录下的 golang1.26 复制到 feeds 目录，并改名 golang
+        rm -rf feeds/packages/lang/golang
+        cp -rf "$GITHUB_WORKSPACE/golang1.26" feeds/packages/lang/golang
+        
+        # 2. 删除临时目录，确保系统重新扫描新 replace 进来的 Makefile
+        rm -rf tmp
+
+        # 3. 检查是否成功替换 Golang1.26 版本，如果退出，说明 golang 版本与 Passwall 要求的 golang 版本对不上。通过以下方法确认版本已经不一致，请打开 https://github.com/Openwrt-Passwall/openwrt-passwall-packages，打开 geoview/Makefile 文件，搜索“golang”并获取相关路径：/feeds/packages/lang/golang/golang-package.mk，确认能在本地仓库 golang1.26 目录下找到“golang-package.mk”文件，且路径一致，否则就是版本对不上（运行脚本将 golang1.26 目录复制并改名为 golang，所以路径等于文件中的 /feeds/packages/lang/golang 目录）
+        echo "=== 检查是否成功替换 Golang1.26 版本 ==="
+        grep -E "PKG_VERSION:=" feeds/packages/lang/golang/golang1.26/Makefile || {
+          echo "ERROR: golang1.26 替换失败！"
+          exit 1
+        }
+        
+    - name: Install feeds（安装 feeds）
+      working-directory: /builder/openwrt
+      run: |
+        ./scripts/feeds install -a
+
+    - name: Install feeds（安装 feeds）
+      working-directory: /builder/openwrt
+      run: |
+        ./scripts/feeds install -a
+
+       # ======== 1. 编译 OpenClash 最新版，（使用 package 编译法）推荐 =========
        # 不推荐使用写入 ./feeds.conf.default 编译法
        # immortalwrt 插件库已经包含 OpenClash，若源码被删除或编译 OpenClash 最新版，使用以下命令自行编译，打开 immortalwrt官方插件库查询：https://github.com/immortalwrt/immortalwrt（选择 openwrt-24.10分支，打开 feeds.conf.default文件，再打开luci仓库找到“applications”查询插件）
     #- name: Import Official Recommended OpenClash
@@ -180,7 +199,7 @@ jobs:
         # 删除临时目录
     #    rm -rf /tmp/OpenClash && rm -rf tmp
 
-       # ======== 2. 编译 Passwall 最新版，使用 package 编译法（置于更新和安装 feeds 命令之间）推荐 =========
+       # ======== 2. 编译 Passwall 最新版，使用 package 编译法（使用 package 编译法）推荐 =========
        # 不推荐使用写入 ./feeds.conf.default 编译法
        # immortalwrt 插件库已经包含 OpenClash，若源码被删除或编译 Passwall 最新版，使用以下命令自行编译，打开 immortalwrt官方插件库查询：https://github.com/immortalwrt/immortalwrt（选择 openwrt-24.10分支，打开 feeds.conf.default文件，再打开luci仓库找到“applications”查询插件）
     - name: Import Official Recommended Passwall
@@ -197,33 +216,17 @@ jobs:
         # 删除临时目录
         rm -rf tmp
 
-       #======= 解决 Passwall 的 Geoview/Xray-core 报错问题（置于更新和安装 feeds 命令之间）=======
-    - name: 升级 Passwall 工具链为 Golang 1.27
+       #======= 编入第三方 msd_lite 插件，解决 IPTV 卡顿（置于更新和安装 feeds 命令之间）=======
+    - name: 编入第三方 msd_lite 插件
       working-directory: /builder/openwrt
       run: |
-        # 1. 直接将本地仓库根目录下的 golang1.27 复制到 feeds 目录，并改名 golang
-        rm -rf feeds/packages/lang/golang
-        cp -rf "$GITHUB_WORKSPACE/golang1.27" feeds/packages/lang/golang
-        
-        # 2. 删除临时目录，确保系统重新扫描新 replace 进来的 Makefile
+        rm -rf feeds/packages/net/msd_lite
+        rm -rf feeds/luci/applications/luci-app-msd_lite
+        git clone https://github.com/ximiTech/msd_lite.git package/msd_lite
+        git clone https://github.com/ximiTech/luci-app-msd_lite.git package/luci-app-msd_lite
+
+        # 删除临时目录
         rm -rf tmp
-
-        # 3. 检查是否成功替换 Golang1.27 版本，如果退出，说明 golang 版本与 Passwall 要求的 golang 版本对不上。通过以下方法确认版本已经不一致，请打开 https://github.com/Openwrt-Passwall/openwrt-passwall-packages，打开 geoview/Makefile 文件，搜索“golang”并获取相关路径：/feeds/packages/lang/golang/golang-package.mk，确认能在本地仓库 golang1.27 目录下找到“golang-package.mk”文件，且路径一致，否则就是版本对不上（运行脚本将 golang1.27 目录复制并改名为 golang，所以路径等于文件中的 /feeds/packages/lang/golang 目录）
-        echo "=== 检查是否成功替换 Golang1.27 版本 ==="
-        grep -E "PKG_VERSION:=" feeds/packages/lang/golang/golang1.27/Makefile || {
-          echo "ERROR: golang1.27 替换失败！"
-          exit 1
-        }
-        
-    - name: Install feeds（安装 feeds）
-      working-directory: /builder/openwrt
-      run: |
-        ./scripts/feeds install -a
-
-    - name: Install feeds（安装 feeds）
-      working-directory: /builder/openwrt
-      run: |
-        ./scripts/feeds install -a
                 
     - name: Configuration Customization - Build_ax6000_immortalwrt_237_golang_msd_lite_110m 
       run: |
